Modified Japanese translation
processing/p5.js-web-editor pull request #1670
Opened 2020-11-11 01:00 UTC by koji

Fixes #issue-number

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

2020-11-11 01:12 UTC, koji commented
@micuat
@deconbatch
@takawo
@sugi2000

Updated items(JSON file) that were pointed out by Naoto HIÉDA san. The following link still has some comments on the translation. I would like to hear your thought.
Thanks!


Naoto HIÉDAさんから頂いた指摘を反映させました。
下記のリンクのコメントについて、他の方の意見を伺えればと思います。
よろしくお願いします。

https://github.com/processing/p5.js-web-editor/pull/1664/files

特に、共有 or シェアについて
Facebook, Instagram: シェア
Google, Youtube: 共有

2020-11-11 01:58 UTC, sugi2000 commented
@koji 日本語化すばらしいです。
・「共有」が一般的かなとおもいます。
・「下さい」は「ください」に統一してはいかがでしょうか。

2020-11-11 17:41 UTC, catarak commented
Yay! Just remove the draft status from this PR when it's ready to be merged 😄

2020-11-13 09:59 UTC, micuat requested changes
細かい点など、docker で実際に使用してみての感想です

2020-11-13 09:59 UTC, micuat commented on translations/locales/ja/translations.json
>        "NoSketches": "スケッチはありません"
コレクション「が」ありません
なのでどちらかに統一したほうがよさそうです

2020-11-13 09:59 UTC, micuat commented on translations/locales/ja/translations.json
>        "LoginOr": " or ",
もしくは

2020-11-13 09:59 UTC, micuat commented on translations/locales/ja/translations.json
> +      "SignUp": "アカウント作成",
> ログイン もしくは アカウント作成.

と表示されるので、「アカウントを作成する」のほうがきれいかもしれません

2020-11-13 09:59 UTC, micuat commented on translations/locales/ja/translations.json
> +      "SignUp": "アカウント作成",
ちなみにこんな感じ

![image](https://user-images.githubusercontent.com/1835081/99059402-d72c5780-259e-11eb-8e1b-640e12513f4c.png)

それとは別に、メニューの方は「アカウント作成」のままでいいと思います（あるいは「アカウントを作成」）

![image](https://user-images.githubusercontent.com/1835081/99059468-ec08eb00-259e-11eb-9143-fbdeda978763.png)

2020-11-13 09:59 UTC, micuat commented
あと、ここは「リファレンス（英語）」としたほうがいいかも
https://github.com/processing/p5.js-web-editor/blob/df6cbff81f5a8b0a914b82c146c31bb326a4cbd5/translations/locales/ja/translations.json#L31

2020-11-13 16:45 UTC, catarak commented
It's hard for me to tell if this is ready to be merged or there's still a few remaining comments from @micuat. @koji let me know?

2020-11-13 17:14 UTC, koji commented
@catarak 
I need to update the JSON file to reflect his feedback. Once everything is done, I will let you know.
Thanks!

2020-11-13 17:16 UTC, micuat commented
@catarak thanks, I think I have a member permission so once it's ready I can "approve" the pull request then you can merge it - does that sound good?

2020-11-13 18:45 UTC, koji commented on translations/locales/ja/translations.json
> +      "SignUp": "アカウント作成",
ありがとうございます。

2020-11-13 18:50 UTC, koji commented
> リファレンス（英語）
ああ、確かにそっちの方が親切ですね。

2020-11-13 19:25 UTC, koji commented on translations/locales/ja/translations.json
> +      "SignUp": "アカウント作成",
`アカウントを作成してください`とかの方がUIの文言としては自然ですかね？

2020-11-13 19:55 UTC, micuat commented
丁寧語で統一するのいいアイディアだと思います！

Looks good, should we wait for more comments or merge now? Unless there is an obvious fix, I think we should finish reviewing and if there is something to fix we can open a new issue/pr.

2020-11-13 20:01 UTC, koji commented
I think we can go forward.
Yeah, I agree with you. We can open a new issue/pr to fix an issue.
Anyway, thank you for your help. Really appreciate🙏

2020-11-13 20:04 UTC, micuat approved these changes
finished revision!

2020-11-13 20:07 UTC, micuat approved these changes
(i'm retrying because i might have submitted review on the wrong commit)

...so obviously I don't have permission to approve 🤣

2020-11-13 20:49 UTC, catarak approved these changes

2020-11-13 20:49 UTC, merged

2020-11-13 20:53 UTC, catarak commented
yay! so excited this translation is done. when i deploy this i'm gonna post about it on the p5.js twitter 😄