Made folder names clickable
processing/p5.js-web-editor pull request #1716
Opened 2020-12-17 16:22 UTC by SundeepChand

Fixes #1712

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Hello @catarak, please review this.

2020-12-17 22:23 UTC, catarak commented
Thanks for working on this! Upon review, I don't like the way that the file name stays focused after you click on it, and I've been thinking about what would be better:
- I don't like that when you click on the open/close folder button, it loses focus. This is because each button is being show/hidden on click. I guess the solution would be to keep the button, but instead show/hide the icon and change the aria text.
- On clicking the folder name, maybe the focus could be blurred? Or the focus should be the whole row.

2020-12-22 16:27 UTC, SundeepChand commented
Hi @catarak, I've made the changes. But it seems like something is wrong with the commit history.

2021-01-04 23:00 UTC, catarak requested changes

2021-01-04 23:00 UTC, catarak commented on client/modules/IDE/components/FileNode.jsx
> +                  className={folderButtonClass}
I think maybe this should have `focusable=false`? I don't like that when you tab through the sidebar, you can focus on the folder name, it feels superfluous for keyboard users when you can just click on the arrow to the left!

2021-01-05 13:58 UTC, SundeepChand commented
Hello @catarak, I've made the changes, however, the folder options icon does not show up unless, the folder is toggled open/close.
May I know what does [this](https://github.com/processing/p5.js-web-editor/blob/61a9cb4f637dca60dc12368a8be0de26be210b7a/client/styles/components/_sidebar.scss#L67) comment mean? In order to fix the problems with folder options icon, it makes sense to move the hover functionality into JS.

2021-02-20 18:50 UTC, SundeepChand commented
Hello @catarak, please review the changes made so far. There are certain minor bugs, that I'm trying to fix.

2021-03-03 21:40 UTC, catarak commented
@SundeepChand I noticed this bug too! I'm not currently able to reproduce it on the `develop` branch so I _think_ it might be related to this PR, but I would double check me.

2021-03-03 21:46 UTC, catarak commented
> May I know what does [this](https://github.com/processing/p5.js-web-editor/blob/61a9cb4f637dca60dc12368a8be0de26be210b7a/client/styles/components/_sidebar.scss#L67) comment mean? In order to fix the problems with folder options icon, it makes sense to move the hover functionality into JS.

If you hover over a file that is in a folder, you'll notice that the folder is also highlighted. I tried to a while to figure out how to generate the SCSS style so this wouldn't happen, but I couldn't figure it out. I bet this would be solved by switching to styled components (see #1760).

2021-03-18 11:32 UTC, Ajaya1000 commented
@catarak I found out how to solve this.
![Screenshot from 2021-03-18 16-46-19](https://user-images.githubusercontent.com/43005088/111618250-26fb8380-880a-11eb-8eb9-57ac5759327f.png)
![gitub](https://user-images.githubusercontent.com/43005088/111618847-dc2e3b80-880a-11eb-9e14-8b53d1a74e10.png)

I'm also working on issue #1760 . So I'll again do it on that branch too.

2021-03-22 04:00 UTC, Ajaya1000 commented
@catarak  should I create another issue for the hover effect??

2023-04-18 18:55 UTC, raclim commented
Thank you so much for taking the time to contribute to this issue—I'm sorry we couldn't get to your work in time! Since some time has passed I'm going to close this for now, but please feel free to reopen this or work on this again, thanks!

2023-04-18 18:55 UTC, closed without merging