UI changes according to available designs in zeplin
processing/p5.js-web-editor pull request #2162
Opened 2023-03-11 19:50 UTC by dewanshDT

Changes:
![designimprovements](https://user-images.githubusercontent.com/71703033/224508473-d75d6f3e-3edf-4780-a994-313542137ddc.png)

![image](https://user-images.githubusercontent.com/71703033/224508546-f7e3a520-70e9-4872-8d52-491b83fd9f5b.png)

These changes are made in accordance with the [available designs](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3).
I implement this because these subtle changes look much better than the UI currently in use.

looking forward to your feedback on this @raclim @lindapaiste

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

2023-03-12 10:02 UTC, 3ru requested changes
It would be nice to have pictures of the UI changes before and after.

2023-03-12 10:02 UTC, 3ru commented on server/views/index.js
> +        };
These unnecessary differences should be removed.

Or was the formatting not applied before?

2023-03-13 06:17 UTC, dewanshDT commented on server/views/index.js
> +        };
the formatting was not applied before
and the screenshots are captured after the changes.

2023-03-22 04:56 UTC, dewanshDT commented
this is before and after the changes.
### Before:
![image](https://user-images.githubusercontent.com/71703033/226805413-6017b01e-8b9d-4206-a4be-23cd8b493618.png)

### After:
![smalldesignimprovements](https://user-images.githubusercontent.com/71703033/226805646-f9c6c7bd-27aa-4f11-bd49-d7b800ece35e.png)

changes made with reference to [these design files](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3)

hey @3ru check this out, any suggestions are welcome 😃

2023-06-28 20:11 UTC, raclim commented
Thanks so much for taking the time to work on this, I really appreciate it! 

Since the zeplin designs are a little outdated, we were considering doing another redesign in the future. With this in mind, I don't think we're ready to make these UI changes yet, so I'm going to close this for now. We'll probably post an issue regarding any design updates, so please feel free to reference and work on those when it happens!

2023-06-28 20:11 UTC, closed without merging