The complete Korean language translation of keyboard shortcuts
processing/p5.js-web-editor pull request #2331
Opened 2023-07-27 13:55 UTC by sdivyanshu90

Fixes: Keyboard Shortcuts

- I have noticed that the Korean translation of the keyboard shortcut is not complete. 
- It can be confusing and frustrating when trying to use certain keyboard shortcuts because some of the key labels are still in English.
<img width="266" alt="image" src="https://github.com/processing/p5.js-web-editor/assets/97019230/08d1e2f0-2011-49c0-a7bf-fc6df0d52451">

Changes:
- I have translated the keyboard shortcuts into the Korean language.

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

2023-07-27 14:04 UTC, sdivyanshu90 commented
Hi @lindapaiste, could you review my pull request and provide feedback? Thanks!

2023-07-28 02:22 UTC, lindapaiste commented
@sdivyanshu90 the PR looks good 👍🏻 

Hopefully someone who knows Korean can check it over and verify that the translations are correct.

2023-08-03 18:09 UTC, raclim requested changes
Overall great start! The translations mostly seem fine to me, but some of the word choices might not make sense in a coding environment. I would update some of them in the lines I noted!

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "Tidy": "깔끔한",
Would change to "정돈하기"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "FindNextMatch": "다음 경기 찾기",
Would change to "다음 일치 항목 찾기"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "FindPrevMatch": "이전 경기 찾기",
Would change to "이전 일치 항목 찾기"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "ReplaceTextMatch": "텍스트 일치 바꾸기",
Would change to "텍스트 일치 항목 바꾸기"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "CommentLine": "댓글 라인",
Would change to "주석 처리"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "FindNextTextMatch": "다음 텍스트 일치 찾기",
Would change to "다음 텍스트 일치 항목 찾기"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "FindPreviousTextMatch": "이전 텍스트 일치 찾기",
Would change to "이전 텍스트 일치 항목 찾기"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +    "SublimeText": "숭고한 텍스트 단축키",
Would change to "서블라임 텍스트"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "TurnOnAccessibleOutput": "접근 가능한 출력 켜기",
Would change to "접근 가능한 출력 활성화"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +      "TurnOffAccessibleOutput": "액세스 가능한 출력 끄기"
Would change to "접근 가능한 출력 비활성화"

2023-08-03 18:09 UTC, raclim commented on translations/locales/ko/translations.json
> +    "ShortcutsFollow": "코드 편집 키보드 단축키는 다음과 같습니다",
Would change to "코드 편집 키보드 단축키는 다음과 같습니다"

2023-08-05 07:00 UTC, sdivyanshu90 commented
Thank you for your review, @raclim! I've implemented all the mentioned changes.

2023-08-07 16:49 UTC, raclim approved these changes
Looks great, thanks so much for your work on this!

2023-08-07 16:50 UTC, merged