Added styled component to AddToCollectionList component
processing/p5.js-web-editor pull request #2368
Opened 2023-08-08 17:36 UTC by adityagarg06

Changes:
Added styled component to AddToCollectionList component.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

2023-08-08 17:52 UTC, adityagarg06 commented
Hi @lindapaiste, I didn't see your PR #2353 before making this PR. I will make the changes later when you will merge the AddCollectionList and AddCollectionSketchList components.

2023-08-08 21:06 UTC, lindapaiste commented
@adityagarg06 Sure thing.  We can merge either my PR or yours first and then fix the conflicts that show up.  Realistically your PR gets merged first.

We have two components which are really similar (and it's confusing which is which!) but they both use these same two CSS classes which you converted.  Maybe we do some sort of shared wrapper at some point, but for now I think you should `export` your two styled components and also use them in the [`AddToCollectionSketchList.jsx`](https://github.com/processing/p5.js-web-editor/blob/develop/client/modules/IDE/components/AddToCollectionSketchList.jsx).  Then you can delete those classes from the CSS.

If we want to make an improvement to the CSS while we're in here, how about we change it from:
```
min-width: ${remSize(600)};
```
to:
```
width: ${remSize(600)};
max-width: 100%;
```
That will help a lot with responsiveness.

2023-08-08 21:51 UTC, lindapaiste requested changes
I'm playing around with the github suggestions tool!

2023-08-08 21:51 UTC, lindapaiste commented on client/modules/IDE/components/AddToCollectionList.jsx
> +const CollectionAddSketchWrapper = styled.div`
```suggestion
export const CollectionAddSketchWrapper = styled.div`
```

2023-08-08 21:51 UTC, lindapaiste commented on client/modules/IDE/components/AddToCollectionList.jsx
> +    min-width: ${remSize(600)};
```suggestion
    width: ${remSize(600)};
    max-width: 100%;
```

2023-08-08 21:51 UTC, lindapaiste commented on client/modules/IDE/components/AddToCollectionList.jsx
> +  &&& {
It doesn't really matter but I suspect that you'd be fine without the `&&&`?

2023-08-08 21:51 UTC, lindapaiste commented on client/modules/IDE/components/AddToCollectionList.jsx
> +    min-width: ${remSize(600)};
```suggestion
    width: ${remSize(600)};
    max-width: 100%;
```

2023-08-13 22:22 UTC, lindapaiste approved these changes
Perfect! Thank you.

2023-08-13 22:22 UTC, merged