Account Settings Page UI for mobile devices
processing/p5.js-web-editor pull request #2400
Opened 2023-09-09 21:22 UTC by dewanshDT

Changes:

Account Settings Page UI Update in small devices
![image](https://github.com/processing/p5.js-web-editor/assets/71703033/605aac4c-05de-4dce-8a49-7585d4c31107)

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.

2023-09-17 23:55 UTC, lindapaiste requested changes

2023-09-17 23:55 UTC, lindapaiste commented on client/styles/components/_forms.scss
> +  width: 100%;
This change has unintended consequences as it's used on all form inputs.  Check out the login and signup pages on desktop.  We might need an override that it specific to the account settings page.

2023-09-20 15:44 UTC, dewanshDT commented on client/styles/components/_forms.scss
> +  width: 100%;
hey @lindapaiste, sorry for late response, I just fixed the problem, please check it out

2023-11-07 00:40 UTC, lindapaiste approved these changes

2023-11-07 00:43 UTC, merged