Fixing the Login Page
processing/p5.js-web-editor pull request #2452
Opened 2023-09-18 05:41 UTC by rajatmohan22

Fixes #2228 

Upon some investigation, I found that the `value` prop of  the input field in a web form is not able to recognize Google Autocomplete with a password manager. Seems like it is bypassing Reacts state management.

[screen-capture.webm](https://github.com/processing/p5.js-web-editor/assets/77490034/0b17027c-bf25-4873-9256-40bcb9d38c50)

Changes:

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

2023-09-18 17:52 UTC, lindapaiste requested changes
Looks good but let's clean up the `import` line before merging.

2023-09-18 17:52 UTC, lindapaiste commented on client/modules/User/components/LoginForm.jsx
> +import React, { useEffect, useState } from 'react';
```suggestion
import React from 'react';
```

2023-09-18 17:52 UTC, lindapaiste commented on client/modules/User/components/LoginForm.jsx
> +          <Button type="submit" disabled={submitting}>
Awesome!

I wish there was some way that the `react-final-form` package would know that the field is not `pristine` when it's been autofilled.  But I don't think that's possible?  So this is the best solution.

2023-09-18 18:14 UTC, rajatmohan22 commented on client/modules/User/components/LoginForm.jsx
> +          <Button type="submit" disabled={submitting}>
Exactly. 

> Awesome!
> 
> This seems like the best solution. I wish there was some way that the `react-final-form` package would know that the field is not `pristine` when it's been autofilled. But I don't think that's possible? When I look at the HTML of the page in dev tools I see that the `value` prop of the inputs is not set when autofilled if the page has not been clicked yet. Then as soon as I click the window the `input` changes from `value` to `value="lindapaiste@gmail.com"`. It's very strange because I don't understand how Chrome is able to display the value without injecting it into the HTML.

I agree. It seems like a browser security measure aimed at preventing data harvesting threats. They may be trying to avoid situations where websites could exploit automatic form filling to collect sensitive user data without their consent.

If you visit Amazon's login page, you'll notice a similar login page behavior where the login button isn't disabled in the Pristine stages ( probably due to the same reasons ).

2023-09-18 18:15 UTC, rajatmohan22 commented on client/modules/User/components/LoginForm.jsx
> +import React, { useEffect, useState } from 'react';
Done !

2023-09-19 05:11 UTC, rajatmohan22 commented
@lindapaiste could you have a look? I also feel that we need to make sure that the value prop when i inspect the page doesn't hold the actual value of the entered password (which is currently happening).

We could use a hash+salt instead. However, I feel we could have a different PR for that

2023-09-20 16:06 UTC, rajatmohan22 commented
@lindapaiste I was wondering if we could disable the value prop for the password field. I feel it is kind of unsafe to have it record the value that the user types.

Could we do something like this?:

`<Field name="password">
            {(field) => {
              const { value, ...restOfFieldInput } = field.input;
              return (
                <p className="form__field">
                  <label htmlFor="password" className="form__label">
                    {t('LoginForm.Password')}
                  </label>
                  <input
                    className="form__input"
                    aria-label={t('LoginForm.PasswordARIA')}
                    type="password"
                    id="password"
                    autoComplete="current-password"
                    value={console.log(field.input.value)}
                    {...restOfFieldInput}
                  />
                  {field.meta.touched && field.meta.error && (
                    <span className="form-error">{field.meta.error}</span>
                  )}
                </p>
              );
            }}
          </Field>`

2023-09-20 17:45 UTC, rajatmohan22 commented
@lindapaiste, could you please take a look? I've removed unnecessary imports. The only thing I believe needs attention is the 'value' prop storing the user's input. Do you think it's safe to leave it this way, or should I make changes here if necessary?

2023-09-21 08:14 UTC, lindapaiste commented
I don’t think that the value prop is a problem?  You can definitely research what the best practices are for dealing with an input type=“password”, but let’s tackle that in a separate PR.

If it’s easy, can you roll back the changes in the package-lock.json file and in the Button file?  It’s it’s a pain then no worries.

2023-09-21 08:39 UTC, rajatmohan22 commented
> I don’t think that the value prop is a problem? You can definitely research what the best practices are for dealing with an input type=“password”, but let’s tackle that in a separate PR.
> 
> If it’s easy, can you roll back the changes in the package-lock.json file and in the Button file? It’s it’s a pain then no worries.

Oh no problem, It's done!

2023-09-21 11:54 UTC, rajatmohan22 commented
@lindapaiste, not a problem at all. I've rolled them back. My apologies for missing that.

2023-09-21 15:18 UTC, lindapaiste approved these changes, later dismissed

2023-09-21 15:26 UTC, lindapaiste commented
We’re just about ready to merge but it’s failing lint checks due to a formatting issue.  We use a package called Prettier so that all code is formatted nicely and consistently.  Now that you removed one of the destructured properties, Prettier thinks that it should all be on one line instead of on separate lines.  If you run the `lint-fix` command that should take care of it.

2023-09-21 16:03 UTC, rajatmohan22 commented
> We’re just about ready to merge but it’s failing lint checks due to a formatting issue. We use a package called Prettier so that all code is formatted nicely and consistently. Now that you removed one of the destructured properties, Prettier thinks that it should all be on one line instead of on separate lines. If you run the `lint-fix` command that should take care of it.

Thanks, i think that did it.

2023-09-21 18:03 UTC, lindapaiste approved these changes

2023-09-21 18:03 UTC, merged