My Staff List can now be read on mobile devices.
processing/p5.js-web-editor pull request #2626
Opened 2023-11-21 17:13 UTC by shibomb

Fixes #2625

Changes:
The background color of each line of the staff list on mobile devices has been set to a darker.

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

2023-11-21 22:11 UTC, lindapaiste requested changes
Awesome!  Can you please apply this to the `contrast` theme too?

Just a note that we need to be careful when changing theme variables because they can be used in multiple places.  In this case it seems like it's only used here so no issue.

2023-11-22 07:04 UTC, shibomb commented
Thanks for reviewing!

I set the contrast theme value to "darker" ;-)
Could you re-review?

2023-11-22 10:39 UTC, PiyushChandra17 approved these changes
Looks good 👍

2023-11-24 18:46 UTC, lindapaiste approved these changes
🌞 🌚

2023-11-24 18:46 UTC, merged