Solved issue #3280
processing/p5.js-web-editor pull request #3288
Opened 2024-12-01 15:47 UTC by Harshit-7373

"npm run test" failing inside docker just after cloning the project #3280.

github-Harshit-7373

Fixes #issue-number

Changes:
1. After i run "npm run test" , it didn't run and showed that the jest command is not recognized.
2. I updated the jest dependencies to the latest and then run "npm run test"
3. It successfully runned without any issue.

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

2024-12-05 17:25 UTC, raclim requested changes
Thanks for your work on this! 

I'm running the tests within my Docker environment with the `Jest` upgrade to `27.5.1` and am still running into my tests failing. Would you be able to provide more screenshots or a demonstrative video of how you're running it? Thanks!

2024-12-05 17:25 UTC, raclim commented on Solved issue image/Screenshot 2024-12-01 at 9.03.43 PM.png
Ideally, screenshots that help show an issue's resolution should be attached to the PR's description rather than as a folder within the codebase. It'd be great if you could remove this folder and screenshot and add the screenshot instead into your PR's description!

2024-12-05 17:28 UTC, raclim commented on Solved issue image/Screenshot 2024-12-01 at 9.03.43 PM.png
It would also be great if you could note any major changes you think are important to be aware of between version `27.3.1` to `27.5.1`!

2024-12-05 17:32 UTC, Harshit-7373 commented on Solved issue image/Screenshot 2024-12-01 at 9.03.43 PM.png
Actually , There are many issues that end up because of the version not been updated to up to date. And that is why i was thinking to modify the .env file and create a prebuild function before running the project where that javascript function will control the version control system. If the version differs in some or the other way , it can automatically run it . Need some views on this , if you could help me out. Also there is a way , to resolve this version issue using docker.

2024-12-05 17:37 UTC, Harshit-7373 commented on Solved issue image/Screenshot 2024-12-01 at 9.03.43 PM.png
> Ideally, screenshots that help show an issue's resolution should be attached to the PR's description rather than as a folder within the codebase. It'd be great if you could remove this folder and screenshot and add the screenshot instead into your PR's description!


Yes , I removed that folder , I understood my mistake and i can assure you this will not happen in the upcoming days.

2024-12-05 17:38 UTC, Harshit-7373 commented
> Thanks for your work on this!
> 
> I'm running the tests within my Docker environment with the `Jest` upgrade to `27.5.1` and am still running into my tests failing. Would you be able to provide more screenshots or a demonstrative video of how you're running it? Thanks!

Sure , Just give me some time i will surely help you solve this issue.

2025-01-16 16:26 UTC, raclim commented
I wanted to update that after taking a closer look into this issue, it seems to be stemming from one of the packages we have installed, `react-refresh-webpack-plugin`, running in tandem with the tests. This plugin is intended to support the developer experience by hot reloading the React components on code changes, but probably shouldn't be active when running tests. I think updating the webpack configuration files will resolve this. 

Since it's been a while from the last updates and the solution seems to be different from what's proposed in this PR, I'm going to close this for now. I'm sorry that we couldn't get this one in, but please feel free to reopen this with any updated changes or check out the other issues!

2025-01-16 16:26 UTC, closed without merging

2025-02-08 20:06 UTC, Harshit-7373 commented
Sorry for the delayed response. This issue is still unresolved. However, I took some time to dive deeper into it and have found a potential approach to solve the issue. I’ve shared my thoughts in the comment section of this [https://github.com/processing/p5.js-web-editor/issues/3190](url)

Please take a look at the thoughts I've mentioned and let me know your Suggestions/thoughts on it .